### ISSUE TITLE
GET /books fails

### ISSUE THREAD

**Issue by wonderdogone** [hemanth/koa-rest#1]
app.js loads up and serves but making a request to /books crashes the server

  xxx GET /books 500 8ms -

  Error: failed to connect to [localhost:27017]

**Comment by hemanth** [comment]
Please make sure you have `mongo` up and running.

**Comment by hemanth** [comment]
@wonderdogone Updated the readme for you :)

Make sure you have mongo running and then `mongoimport -d library -c books ./db.json`

**Comment by wonderdogone** [comment]
awesome thanks...

**Comment by hemanth** [comment]
Do check out the live demo ;)
